export const USER_DATA = {
  GESubject: [
    {
      year: 2021,
      discussion: 10,
      take_subject_id: '20210985-006002',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      major: '차미리사교양대학 교학과(학사)',
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      professor: '이용민',
      subject_name: '덕성인의기초',
      team_play: 0,
      subject_hour: 0,
      subject_rating: 4.87,
      subject_code: '006002',
      semester: 1,
      credit: 1,
      subject_classification: '기초',
      subject_difficulty: 1.0,
    },
    {
      major: '철학전공',
      year: 2021,
      geclassification: 'A2영역',
      user_student_number: '20210685',
      professor: '변문숙',
      subject_classification: '융합(계열)',
      take_subject_id: '20210685-501958',
      completion_grade: 1,
      subject_code: '501958',
      completion_semester: 1,
      grade: '1~4',
      presentation: 0,
      subject_name: '윤리란무엇인가?',
      team_play: 0,
      subject_hour: 0,
      semester: 1,
      credit: 3,
      discussion: 20,
      subject_difficulty: 2.0,
      subject_rating: 4.38,
    },
    {
      year: 2021,
      professor: '정무정',
      subject_rating: 5.0,
      user_student_number: '20210685',
      subject_classification: '융합(계열)',
      completion_grade: 1,
      discussion: 0,
      major: '차미리사교양대학 교학과(학사)',
      subject_name: '색채심리와현대생활',
      completion_semester: 1,
      subject_code: '501784',
      presentation: 0,
      team_play: 0,
      take_subject_id: '20210685-501784',
      subject_hour: 0,
      geclassification: 'B영역',
      semester: 1,
      credit: 3,
      grade: '2~4',
      subject_difficulty: 4.0,
    },
    {
      year: 2021,
      subject_name: '영어회화',
      major: '글로벌커뮤니케이션센터(학사)',
      subject_rating: 4.17,
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      subject_code: '501821',
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      discussion: 25,
      team_play: 0,
      professor: '채드',
      subject_hour: 0,
      take_subject_id: '20210685-501821',
      semester: 1,
      subject_classification: '기초',
      credit: 2,
      subject_difficulty: 1.0,
    },
    {
      subject_rating: 4.94,
      year: 2021,
      subject_code: '501818',
      presentation: 20,
      grade: '1',
      professor: '오자은',
      user_student_number: '20210685',
      completion_grade: 1,
      major: '소통역량개발센터(학사)',
      geclassification: '',
      subject_name: '이해와소통세미나',
      take_subject_id: '20210685-501818',
      completion_semester: 1,
      team_play: 0,
      subject_hour: 0,
      discussion: 30,
      semester: 1,
      subject_classification: '기초',
      credit: 3,
      subject_difficulty: 1.0,
    },
    {
      subject_rating: 4.14,
      year: 2021,
      discussion: 10,
      take_subject_id: '20210685-502090',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      completion_semester: 2,
      geclassification: '',
      presentation: 0,
      subject_name: '나의진로나의꿈',
      team_play: 0,
      professor: '장승환',
      subject_hour: 0,
      major: '대학일자리본부(학사)',
      semester: 2,
      subject_code: '502090',
      credit: 1,
      subject_classification: '기초',
      subject_difficulty: 1.0,
    },
    {
      year: 2021,
      take_subject_id: '20210685-501809',
      subject_code: '501809',
      geclassification: 'A3영역',
      user_student_number: '20210685',
      subject_classification: '융합(계열)',
      subject_name: '현대사회의부족들',
      completion_grade: 1,
      completion_semester: 2,
      professor: '함세정',
      grade: '1~4',
      presentation: 0,
      team_play: 0,
      subject_hour: 0,
      discussion: 30,
      major: '문화인류학전공',
      semester: 2,
      subject_rating: 4.32,
      credit: 3,
      subject_difficulty: 2.0,
    },
    {
      year: 2021,
      subject_name: '전문영어:English through Current Events and News',
      discussion: 40,
      major: '글로벌커뮤니케이션센터(학사)',
      grade: '1',
      user_student_number: '20210685',
      subject_rating: 4.61,
      take_subject_id: '20210685-501826',
      completion_grade: 1,
      subject_code: '501826',
      completion_semester: 2,
      presentation: 30,
      geclassification: '',
      team_play: 0,
      professor: '윌리엄',
      subject_hour: 0,
      semester: 2,
      subject_classification: '기초',
      credit: 3,
      subject_difficulty: 1.0,
    },
    {
      year: 2021,
      grade: '1',
      user_student_number: '20210685',
      major: '융합사고력센터(학사)',
      completion_grade: 1,
      discussion: 0,
      completion_semester: 2,
      subject_name: '컴퓨팅사고',
      take_subject_id: '20210685-006003',
      geclassification: '',
      subject_rating: 2.59,
      presentation: 0,
      subject_hour: 0,
      semester: 2,
      team_play: 10,
      subject_code: '006003',
      professor: '김성애',
      subject_classification: '기초',
      credit: 2,
      subject_difficulty: 1.0,
    },
    {
      year: 2021,
      user_student_number: '20210685',
      subject_classification: '융합(계열)',
      subject_name: '기초3D프로그램',
      take_subject_id: '20210685-501878',
      completion_grade: 2,
      discussion: 0,
      subject_code: '501878',
      completion_semester: 1,
      grade: '1~4',
      team_play: 0,
      subject_hour: 0,
      major: '실내디자인전공',
      semester: 2,
      geclassification: 'C영역',
      presentation: 10,
      subject_rating: 3.81,
      professor: '이미희',
      credit: 3,
      subject_difficulty: 2.0,
    },
    {
      discussion: 10,
      professor: '황인순',
      year: 2022,
      presentation: 20,
      grade: '2',
      user_student_number: '20210685',
      completion_grade: 2,
      major: '소통역량개발센터(학사)',
      geclassification: '',
      subject_name: '대학글쓰기',
      completion_semester: 1,
      team_play: 0,
      subject_hour: 0,
      subject_code: '502120',
      subject_rating: 4.93,
      semester: 1,
      take_subject_id: '20210685-502120',
      subject_classification: '기초',
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      year: 2022,
      user_student_number: '20210685',
      professor: '박진식',
      subject_classification: '융합(계열)',
      completion_grade: 2,
      discussion: 0,
      major: '서양화전공',
      subject_name: '사진의이해',
      completion_semester: 1,
      grade: '1~4',
      presentation: 0,
      take_subject_id: '20210685-501871',
      subject_code: '501871',
      team_play: 0,
      subject_hour: 0,
      geclassification: 'B영역',
      semester: 1,
      subject_rating: 4.32,
      credit: 3,
      subject_difficulty: 2.0,
    },
    {
      professor: '이수호',
      year: 2022,
      subject_name: '노동인권',
      user_student_number: '20210685',
      subject_classification: '설계',
      completion_grade: 2,
      major: '차미리사교양대학 교학과(학사)',
      completion_semester: 2,
      geclassification: '',
      grade: '1~4',
      subject_rating: 4.41,
      team_play: 0,
      take_subject_id: '20210685-502148',
      subject_code: '502148',
      subject_hour: 0,
      presentation: 10,
      semester: 1,
      credit: 3,
      discussion: 20,
      subject_difficulty: 2.0,
    },
    {
      subject_rating: 4.26,
      year: 2022,
      user_student_number: '20210685',
      subject_classification: '융합(계열)',
      completion_grade: 2,
      subject_name: '아트인라이프',
      discussion: 0,
      major: '서양화전공',
      completion_semester: 2,
      grade: '1~4',
      presentation: 0,
      take_subject_id: '20210685-502597',
      subject_code: '502597',
      team_play: 0,
      professor: '안현정',
      subject_hour: 0,
      geclassification: 'B영역',
      semester: 1,
      credit: 3,
      subject_difficulty: 2.0,
    },
    {
      year: 2023,
      subject_rating: 5.0,
      user_student_number: '20210685',
      subject_classification: '설계',
      completion_grade: 3,
      discussion: 0,
      major: '생활체육학전공',
      professor: '김준동',
      subject_name: '트레킹과등산',
      geclassification: '',
      completion_semester: 1,
      grade: '1~4',
      presentation: 0,
      team_play: 0,
      subject_hour: 0,
      subject_code: '502491',
      semester: 2,
      take_subject_id: '20210685-502491',
      credit: 2,
      subject_difficulty: 2.0,
    },
    {
      year: 2023,
      professor: '주은선',
      geclassification: 'A3영역',
      subject_name: '인간관계심리학',
      user_student_number: '20210685',
      subject_classification: '융합(계열)',
      completion_grade: 3,
      discussion: 0,
      completion_semester: 1,
      grade: '1~4',
      major: '심리학전공',
      presentation: 0,
      subject_rating: 2.78,
      team_play: 0,
      subject_code: '502781',
      subject_hour: 0,
      semester: 2,
      credit: 3,
      subject_difficulty: 2.0,
      take_subject_id: '20210685-502781',
    },
  ],
  persondata: {
    userStudentNumber: '20210685',
    userName: '김덕성',
    userFirstMajor: '컴퓨터공학전공',
    userSecondMajor: '시각디자인전공',
    firstMajorHard: false,
    secondMajorHard: false,
    requiredCourseCredit: 15,
    a1Credit: 0,
    a2Credit: 3,
    a3Credit: 6,
    selfDesignCredit: 5,
    baseMajorCredit: 15,
    firstMajorCredit: 24,
    secondMajorCredit: 18,
    restCredit: 31,
    restSemester: 3,
    semester: 6,
    totalCredit: 99,
    gradePointAverage: 3.8,
    teamPlay: false,
    presentation: true,
    discussion: false,
    bcredit: 9,
    ccredit: 3,
    gecredit: 42,
  },
  baseMajorSubject: [
    {
      year: 2021,
      subject_name: '컴퓨터와친해지기',
      subject_classification: '전탐',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      discussion: 0,
      professor: '유견아',
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      subject_hour: 0,
      subject_rating: 4.54,
      take_subject_id: '20210685-502283',
      subject_code: '502283',
      semester: 1,
      credit: 3,
      subject_difficulty: 2.5,
    },
    {
      year: 2021,
      discussion: 10,
      presentation: 20,
      subject_classification: '전탐',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      geclassification: '',
      major: 'IT미디어공학전공',
      completion_semester: 1,
      team_play: 0,
      subject_hour: 0,
      subject_code: '502284',
      subject_rating: 2.27,
      semester: 1,
      subject_name: '테크니컬아트',
      professor: '임양미',
      take_subject_id: '20210685-502284',
      credit: 3,
      subject_difficulty: 2.5,
    },
    {
      year: 2021,
      subject_classification: '전탐',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      major: 'IT미디어공학전공',
      presentation: 0,
      team_play: 0,
      subject_hour: 0,
      subject_rating: 4.7,
      subject_code: '502287',
      semester: 2,
      professor: '엄태원/서민혜',
      subject_name: '프로그래밍기초',
      take_subject_id: '20210685-502287',
      credit: 3,
      subject_difficulty: 2.5,
    },
    {
      year: 2021,
      subject_classification: '전탐',
      grade: '1',
      user_student_number: '20210685',
      completion_grade: 1,
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      major: 'IT미디어공학전공',
      presentation: 0,
      subject_rating: 2.28,
      team_play: 0,
      subject_name: '콘텐츠프로그래밍',
      subject_hour: 0,
      subject_code: '502285',
      professor: '임양규',
      semester: 2,
      take_subject_id: '20210685-502285',
      credit: 3,
      subject_difficulty: 2.5,
    },
    {
      subject_name: '시각디자인의기초',
      year: 2023,
      subject_classification: '전탐',
      subject_rating: 4.0,
      grade: '1',
      user_student_number: '20210685',
      major: '시각디자인전공',
      completion_grade: 1,
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      presentation: 0,
      team_play: 0,
      professor: '이승진/김승민',
      subject_hour: 0,
      subject_code: '502298',
      semester: 2,
      take_subject_id: '20210685-502298',
      credit: 3,
      subject_difficulty: 1.0,
    },
  ],
  success: true,
  firstMajorSubject: [
    {
      year: 2022,
      grade: '2',
      user_student_number: '20210685',
      subject_name: 'C프로그래밍',
      take_subject_id: '20210685-502209',
      subject_code: '502209',
      completion_grade: 2,
      discussion: 0,
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      professor: '이찬수',
      subject_classification: '전선',
      subject_hour: 0,
      subject_rating: 4.51,
      semester: 1,
      credit: 3,
      subject_difficulty: 3.5,
    },
    {
      subject_code: '004737',
      year: 2022,
      grade: '2',
      user_student_number: '20210685',
      subject_name: '인터넷기초',
      completion_grade: 2,
      discussion: 0,
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      take_subject_id: '20210685-004737',
      subject_classification: '전선',
      subject_hour: 0,
      semester: 1,
      subject_rating: 4.75,
      credit: 3,
      professor: '이경미',
      subject_difficulty: 3.5,
    },
    {
      professor: '남송휘',
      year: 2022,
      grade: '2',
      user_student_number: '20210685',
      completion_grade: 2,
      discussion: 0,
      subject_name: '파이썬',
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      subject_code: '502210',
      semester: 1,
      take_subject_id: '20210685-502210',
      credit: 3,
      subject_difficulty: 3.5,
      subject_rating: 3.11,
    },
    {
      subject_code: '004734',
      year: 2023,
      grade: '2',
      user_student_number: '20210685',
      completion_grade: 2,
      professor: '박우창',
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      subject_name: '자료구조론',
      presentation: 0,
      major: '컴퓨터공학전공',
      subject_rating: 3.38,
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      take_subject_id: '20210685-004734',
      semester: 2,
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      year: 2023,
      grade: '2',
      subject_rating: 0.0,
      user_student_number: '20210685',
      completion_grade: 2,
      take_subject_id: '20210685-004740',
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      professor: '유제혁',
      subject_classification: '전선',
      subject_hour: 0,
      semester: 2,
      subject_code: '004740',
      subject_name: '인터넷프로그래밍',
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      year: 2023,
      grade: '2',
      user_student_number: '20210685',
      completion_grade: 2,
      discussion: 0,
      completion_semester: 2,
      geclassification: '',
      presentation: 0,
      major: '컴퓨터공학전공',
      take_subject_id: '20210685-502211',
      team_play: 0,
      professor: '이찬수',
      subject_classification: '전선',
      subject_hour: 0,
      subject_rating: 3.75,
      subject_code: '502211',
      semester: 2,
      subject_name: 'JAVA프로그래밍',
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      subject_code: '004756',
      year: 2023,
      grade: '3',
      user_student_number: '20210685',
      completion_grade: 3,
      discussion: 0,
      professor: '이주영',
      geclassification: '',
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      take_subject_id: '20210685-004756',
      subject_name: '컴퓨터네트워크',
      semester: 1,
      subject_rating: 4.05,
      credit: 3,
      subject_difficulty: 4.0,
    },
    {
      discussion: 10,
      year: 2023,
      grade: '3',
      subject_rating: 0.0,
      user_student_number: '20210685',
      completion_grade: 3,
      subject_code: '005849',
      professor: '방장혁',
      geclassification: '',
      subject_difficulty: 4.5,
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      take_subject_id: '20210685-005849',
      subject_classification: '전선',
      subject_hour: 0,
      subject_name: 'UX디자인',
      semester: 1,
      credit: 3,
    },
    {
      subject_name: '모바일앱프로그래밍',
      year: 2023,
      grade: '3',
      subject_rating: 4.0,
      subject_code: '005425',
      user_student_number: '20210685',
      completion_grade: 3,
      take_subject_id: '20210685-005425',
      discussion: 0,
      geclassification: '',
      subject_difficulty: 4.5,
      completion_semester: 1,
      presentation: 0,
      major: '컴퓨터공학전공',
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      semester: 1,
      credit: 3,
      professor: '이경미',
    },
  ],
  secondMajorSubject: [
    {
      subject_code: '005845',
      subject_name: '컴퓨터그래픽디자인',
      year: 2022,
      grade: '2',
      subject_rating: 4.8,
      user_student_number: '20210685',
      completion_grade: 2,
      major: '시각디자인전공',
      discussion: 0,
      geclassification: '',
      completion_semester: 1,
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      take_subject_id: '20210685-005845',
      presentation: 10,
      semester: 1,
      professor: '이상미',
      credit: 3,
      subject_difficulty: 3.5,
    },
    {
      year: 2023,
      grade: '2',
      subject_rating: 5.0,
      user_student_number: '20210685',
      completion_grade: 2,
      major: '시각디자인전공',
      discussion: 0,
      team_play: 30,
      completion_semester: 2,
      subject_code: '502614',
      geclassification: '',
      presentation: 0,
      subject_classification: '전선',
      subject_hour: 0,
      take_subject_id: '20210685-502614',
      semester: 2,
      subject_name: '3D애니메이션',
      professor: '이형기',
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      year: 2023,
      grade: '2',
      subject_rating: 3.0,
      user_student_number: '20210685',
      completion_grade: 2,
      major: '시각디자인전공',
      professor: '이문선',
      subject_name: '모션그래픽 ',
      discussion: 0,
      subject_code: '502613',
      completion_semester: 2,
      geclassification: '',
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      take_subject_id: '20210685-502613',
      semester: 2,
      presentation: 10,
      credit: 3,
      subject_difficulty: 3.0,
    },
    {
      year: 2023,
      grade: '3',
      subject_code: '502609',
      subject_rating: 4.0,
      user_student_number: '20210685',
      completion_grade: 3,
      major: '시각디자인전공',
      professor: '이문선',
      discussion: 0,
      take_subject_id: '20210685-502609',
      geclassification: '',
      subject_difficulty: 4.5,
      completion_semester: 1,
      team_play: 0,
      subject_classification: '전선',
      subject_hour: 0,
      presentation: 10,
      semester: 1,
      credit: 3,
      subject_name: '모션그래픽 스튜디오',
    },
  ],
};
